#preload = ~/Pictures/Backgrounds/0020.jpg
#if more than one preload is desired then continue to preload other backgrounds
#preload = /path/to/next_image.png
# .. more preloads

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
#wallpaper = DP-3,~/Pictures/Backgrounds/0020.jpg
#if more than one monitor in use, can load a 2nd image
#wallpaper = HDMI-A-1,~/Pictures/Backgrounds/0020.jpg
# .. more monitors

#enable splash text rendering over the wallpaper
splash = false 

#fully disable ipc
# ipc = off

wallpaper {
        monitor = DP-4
        path = ~/Pictures/Backgrounds/0023.jpg
        fit_mode = cover
}

wallpaper {
        monitor = HDMI-A-3
        path = ~/Pictures/Backgrounds/0023.jpg
        fit_mode = cover
}
